name: Notion Media Update

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running the workflow'
        required: false
        default: 'Manual trigger'

  # Schedule to run automatically (e.g., once a day)
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC every day

  # Allows you to trigger this workflow via GitHub API
  repository_dispatch:
    types: [run-notion-update]

jobs:
  update-notion:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python 3.12
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the update script based on input parameter or run all updates if triggered by schedule/API
      - name: Run Notion Media Update
        run: python main.py
        env:

          # Notion API credentials
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}

          # External APIs credentials
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          IGDB_CLIENT_ID: ${{ secrets.IGDB_CLIENT_ID }}
          IGDB_CLIENT_SECRET: ${{ secrets.IGDB_CLIENT_SECRET }}

          # Database configuration
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
